# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c86f30366a20f1b061ca8fc59f6e1c84ceec7d504e169917bfb517deb19251bfd687c3e8e1a21c33d45fa115acb023cbe3a44959b3fd08c67d4e27325d5b8096

test:
  secret_key_base: 0226af3d00604b1fca3c4965b4c2c491c327b933116c576eab212bcfa388189aeaf7428c3f4fad205e3b4445b01644563c357b7a52396c406c901081fcb7c5b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
